language: python
python:
    - "2.7"
#    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
install: 
    - pip install .
    - pip install coveralls
script: 
    nosetests --with-coverage --cover-package=diffr --cover-branches
after_success:
    coveralls
deploy:
    provider: pypi
    user: "grahamegee"
    on:
        tags: true
