language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
install: 
    - pip install .
    - pip install coverage
script: 
    nosetests --with-coverage --cover-package=differ --cover-branches
after_success:
    coveralls
